# data for how to draw a window

# should start with what we are
meta:
    type: WindowBorder

data:
    # a name for the style
    name: normal
    # base image
    image: gui.window

    # how do I split up the image?
    rects:
        top_left: [0, 0, 8, 24]
        top_middle: [8, 0, 8, 24]
        top_right: [16, 0, 8, 24]
        middle_left: [0, 24, 3, 2]
        middle_right: [21, 24, 3, 2]
        bottom_left: [0, 26, 3, 3]
        bottom_middle: [3, 26, 18, 3]
        bottom_right: [21, 26, 3, 3]
    # colour of background
    background: [214, 214, 214]
    dimensions:
        extra_width: 6
        extra_height: 27
        min_width: 24
        min_height: 29
    border_size: 8
